---
# tasks file for /home/ansible/ansible/roles/apache
- name: Install httpd Package
  yum: 
    name: httpd
    state: latest

- name: Open port 80 for http access
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: Restart the firewalld service to load in the firewall changes
  service:
    name: firewalld
    state: restarted

- name: Copy v1 configuration file
  template:
    src: templates/tanos.conf.j2
    dest: /etc/httpd/conf.d/tanos.conf

- name: Copy index.html file
  copy: 
    src: files/index.html 
    dest: /var/www/html
  notify:
    - restart_apache

- name: Start and Enable httpd service
  service: 
    name: httpd 
    state: restarted 
    enabled: yes

