---
- name: Second task for home work
  hosts: all
  tasks:
  - name: Disable  network manager on all hosts
    service:
      name: NetworkManager
      enabled: no
  - name: Changing grub file
    lineinfile:
     path: /etc/default/grub
     regexp: 'GRUB_CMDLINE_LINUX'
     line: GRUB_CMDLINE_LINUX="crashkernel=auto rhgb quie net.ifnames=0 biosdevname=0"
  - name: Applying changes to grub.cfg
    command: grub2-mkconfig